### ISSUE TITLE
Use _Generic if available to print the contents of variables in specialized assertions

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#105]
Currently, `cr_assert_eq(a, b)` will print `a != b` if the assertion fails. It could be nice for the assertion to also print something like `('a' = <value of a>, 'b' = <value of b>)` at the end of the default assertion message.

**Comment by kevinoid** [comment]
What's the status of this feature?  I'd be interested in seeing it implemented and willing to help make it happen.

**Comment by Snaipe** [comment]
@kevinoid No work has been done on the issue, mainly because I have little time these days, and more pressing matters arised for the 2.3.0 release. The main issue to see this implemented correctly is that the current behaviour of `_Generic` is too restrictive to be consistently useful (for instance, `int *` isn't compatible with `void *`, `char []` isn't compatible with `char *`, ...).

There is also the matter of being able to specify the expanded values consistently with and without internationalization.

If I had to give it a go, I would probably try to support all primitive types (and their respective pointer types, plus their const types) with `_Generic`, then for the fallback parse the type name to see if it contains a `*`, and if it does, then use `%p`, otherwise replace the value with `<unprintable>`.

**Comment by kevinoid** [comment]
@Snaipe Thanks for the update.  I agree about the issues with `_Generic`, it's unfortunate.  Your proposed implementation sounds good to me.  I wouldn't mind taking a shot at it to see if I can come up with something useful.  Don't feel obligated to merge the result.

For the implementation I have in mind, it would be convenient to add a value-formatting argument (deduced using `_Generic`) to `cr_assert_impl`.  Would that be considered API breakage and require a major version bump, or is `cr_assert_impl` considered internal-use-only and not part of the API?  Could the `dummy` argument be repurposed?

Thanks!

**Comment by kevinoid** [comment]
I haven't managed to come up with an implementation that I'm happy with, but I wanted to update this issue with the things that I've learned which may be useful to you or to other implementers:

* Using `(Value)+0` as the controlling expression for `_Generic`, rather than `Value`, as described in [N1930](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1930.htm) can be very useful.  It forces an lvalue conversion which removes qualifiers and converts array types to pointer types.  It also promotes integral types, which reduces the type cases (and could be done as a second expansion if special formatting for types such as `_Bool` is desired).  However, it causes `warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]` when used for `void *` on GCC.

* Calling formatting functions inside `_Generic` results in type warnings for unused type cases.  For example:  `int x = 1; _Generic(x, int:printf("%d",x),long:printf("%ld",x));` causes `warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]`.  This can be avoided by using `_Generic` to select the function (e.g. `_Generic(x, int:print_int,long:print_long)(x);`) or formatting argument (e.g. `printf(_Generic(x, int:"%d",long:"%ld"),x);`).

* Since complex types can't be formatted with a single specifier, and some types may be better with custom formats (e.g. `_Bool`), having the macro select a formatting function based on the argument type seems to be preferable.

* I have been unable to find a way to prevent multiple evaluations of the assert macro arguments when printing then comparing their values using only standard C11 constructs.  It appears that this requires compiler extensions such as [the GCC `typeof` operator](https://gcc.gnu.org/onlinedocs/gcc/Typeof.html) (which is supported by Clang and ICC and likely others).

* [P99](http://p99.gforge.inria.fr/) provides [P99_FORMAT](http://p99.gforge.inria.fr/p99-html/group__tgprint_gae16d2bd5effbc6cdbdd480750866223e.html#gae16d2bd5effbc6cdbdd480750866223e) which does exactly what we need.  Unfortunately, it is licensed under the [QPL](https://scm.gforge.inria.fr/anonscm/gitweb?p=p99/p99.git;a=blob_plain;f=LICENSE-QPL.txt;hb=HEAD) which causes practical problems for either using the library or copying its implementation.

I'm afraid the macro magic necessary to implement this robustly and without compiler warnings is a bit beyond my time and abilities at the moment.  So I'd encourage anyone else interested in this feature to have a go at it.

**Comment by Snaipe** [comment]
Thank you for your research. I'm experimenting on my end with means of formatting generic pointer values through binary introspection, both works will most probably help a lot in implementing something sensible.

**Comment by Snaipe** [comment]
This was fixed by #182.
