### ISSUE TITLE
Does Criterion support randomize tests?

### ISSUE THREAD

**Issue by jetm** [Snaipe/Criterion#109]
I looked in the documentation and read about parameterized tests and theories. But I found them unclear, if I can use them to create tests with random data and be reproducible using seeds.

**Comment by a1lu** [comment]
Afaik:
Theories are used to to tests over all permutations of the given datapoints.
Parameterized tests using a finite parameter set.

So you can create "randomized" tests by creating random datapoints or parameters (i.e. with random() ).
Although you have to know the expected or unexpected result of the function to be tested with random parameters.

**Comment by Snaipe** [comment]
I won't add much to what @a1lu said, but parameterized tests are much more fit for this than theories, although there probably isn't a tool that would be fit enough for this purpose.

I don't think that unit testing against random values is generally a good idea, generally. Here's my two cents on the matter:

1. Randomization makes your tests unpredictable, and your failure points not reproducible (unless, of course, you print your seed at the start of your test and provide a mechanism to set this seed, but this is not convenient)
2. Randomization doesn't bring anything substantial to your test suite, because unit tests are not meant to debug your code; they *validate a behaviour* of a set of functions with known parameters.
3. Randomization breaks horribly between platforms, because the values that `rand()` returns for a fixed seed is completely up to the implementation, which means you can only run your tests on your own machine; hardly useful.
4. Randomization is often misused as a mean to test functions that take "any kind of X", where X could be an integer, a floating point number, a structure type, ... in which case, coverage and validation can still be achieved by means of triangulation: use a theory to test your inputs with "interesting" values, and regular tests with arbitrary values.

    Take for instance the [theory sample](https://github.com/Snaipe/Criterion/blob/bleeding/samples/theories.c#L33-L55), where integer multiplication is tested -- we know for a fact that `mul(1, 2)` won't really differ in behaviour than `mul(2, 3)`, so we only test interesting values like `0` or `INT_MAX` because we expect the function to behave similarly with `132873` or `-42987398`. If the implementation had a bug where it somehow aborted for `mul(42, 42)`, the unit tests wouldn't catch it, because that's not something you would expect of the behaviour of the function. *And this is fine.* Use the right tool for the right job, as they say: this is where coverage, fuzzing, and concolic testing are the best.

Now, I'm not saying feeding random data to your program is not a good idea -- but this is the job of a fuzzer, which *should* be used independently of your test suite to track bugs. Unit tests only enforces the rules of your API.

**Comment by jetm** [comment]
Thank you @a1lu and @Snaipe for your good responses.
