### ISSUE TITLE
Scan-build static analyzer reports

### ISSUE THREAD

**Issue by Wiler** [Snaipe/Criterion#133]
Hi,

I got some report in Criterion's code:

 cr_assert_eq(0, 0, "Err %d", 0);

1.--->  Within the expansion of the macro 'cr_assert_eq':
Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption

2.--->  Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119

do { _Bool cr_passed__ = !!((0)==(0)); char *cr_msg__ = ((void
*)0); size_t cr_bufsize__; struct criterion_assert_stats *cr_stat__
; do { char *cr_def_msg__ = cr_translate_assert_msg( CRITERION_ASSERT_MSG_EXPR_FALSE
, "" "(0)==(0)"); char *cr_fmt_msg__ = ((void*)0); int cr_shifted__
 = 0; int cr_msglen__ = cr_asprintf(&cr_fmt_msg__, "x" "Err %d"
, 0); if (cr_fmt_msg__ && cr_fmt_msg__[1]) { cr_msg__
 = cr_fmt_msg__ + 1; cr_shifted__ = 1; --cr_msglen__; free(cr_def_msg__
); } else { cr_msg__ = cr_def_msg__; cr_msglen__ = strlen(cr_def_msg__
); free(cr_fmt_msg__); } cr_bufsize__ = sizeof(struct criterion_assert_stats
) + sizeof(size_t) + cr_msglen__ + 1; char *cr_buf__ = (char *
) malloc(cr_bufsize__); cr_stat__ = (struct criterion_assert_stats
 *)cr_buf__; memset(cr_buf__, 0, sizeof(struct criterion_assert_stats
)); cr_buf__ += sizeof(struct criterion_assert_stats); *((size_t
 *)cr_buf__) = cr_msglen__ + 1; cr_buf__ += sizeof(size_t); strcpy
(cr_buf__, cr_msg__); free(cr_msg__ - cr_shifted__); } while (
0); cr_stat__->passed = cr_passed__; cr_stat__->file = "/x/x.c"
; cr_stat__->line = 54; criterion_send_event(ASSERT, cr_stat__
, cr_bufsize__); free(cr_stat__); if (!cr_passed__) criterion_abort_test
(); } while (0)

**Comment by Snaipe** [comment]
Thank you for these reports, but I'm afraid that those really are false positive.

First, we're constructing a variable-length data buffer that is going to get sent to the runner, so of course, while this is not ideal, we *know* what we are doing. Admitedly this is "fixed" on bleeding since we're no longer crafting a buffer manually, but again this is assuming this needed a "fix" in the first place.

Second, the contract of both `cr_translate_assert_msg` and `cr_asprintf` is to provide *no matter what* a null-terminated string, and the receiving buffer is allocated with the size of the associated string as parameter. `strcpy` is absolutely applicable and doing some more fieldwork to call `strncpy`, `strlcpy` or `strcpy_s` depending on the platform is more trouble than it's worth.

Hence, I won't be fixing those, but I would be interested in having some reports against the `bleeding` branch if you happen to have some.

**Comment by Wiler** [comment]
Ok, I understand, thank you!
