### ISSUE TITLE
Provide a working environment

### ISSUE THREAD

**Issue by edouard-lopez** [Snaipe/Criterion#158]
Hi,
I'm trying to use your lib to do some TDD (test-driven development) but I got little experience using `C` and so far I can't compile my test.

Could you provide a Docker image with the correct configuration and directory structure to run the test?

**Comment by Snaipe** [comment]
Well, criterion should work in pretty much any working environment, provided you have gcc, make, cmake, git, and install the library in `/usr`.

Here's a dockerfile to setup all this:

```
FROM ubuntu:devel

RUN apt-get update

RUN apt-get install -y g++ cmake git

RUN git clone --branch=master https://github.com/Snaipe/Criterion && \
    cd Criterion && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_INSTALL_LIBDIR=lib \
          .. && \
    make && \
    make install && \
    cd ../../ && rm -Rf Criterion
```

You can then try out any of the [samples](https://github.com/Snaipe/Criterion/tree/bleeding/samples).

If you'd like, you could also use the bleeding branch rather than the release by removing the `--branch=master` but keep in mind that you'll have to *explicitely* disable PIEs with `-no-pie` on GCC and LLVM (PIE builds are currently broken)

**Comment by Snaipe** [comment]
Closing this, as I think everything has already been said.
