### ISSUE TITLE
Fix and/or document assert in hooks

### ISSUE THREAD

**Issue by kevinoid** [Snaipe/Criterion#163]
Can `cr_assert*` be used in hooks?  If not, can hooks abort testing when preconditions are not satisfied?  If so, how?

It would be great if assertions were supported in hooks as a means to abort testing.  If this is not desirable, it would be nice if it were documented and if the use of `cr_assert*` in hooks caused a clear and immediate failure/crash to make the user error easier to avoid, diagnose, and fix.

The current behavior appears to depend on the hook in which the assertion appears.  Using the following test program:

``` C
#include <criterion/criterion.h>

Test(sample, test) {
    cr_assert(1);
}

ReportHook(HOOK)(HOOK_ARG_TYPE *arg) {
    (void)arg;
    cr_assert(1);
}
```

The results are:

| Hook | Behavior |
| --- | --- |
| PRE_ALL | `[ERR ] Could not write the "assert" message down the event pipe: Bad file descriptor.` |
| PRE_SUITE | Hang |
| PRE_INIT | Hang |
| PRE_TEST | Hang |
| ASSERT | Works |
| POST_TEST | Hang |
| POST_FINI | Hang |
| POST_SUITE | Hang |
| POST_ALL | Hang |

With the exception of `ASSERT`, none of the behavior appears to be particularly desirable.  If it is unavoidable, some documentation would certainly help make it easier to avoid.

Thanks for considering,
Kevin

**Comment by Snaipe** [comment]
I would say that the ASSERT hook working is more of a coincidence more than an intended behaviour.

Hooks are a bit delicate. They are run on the runner side rather than the test side, and are meant to provide a way for a user to follow the progression of the test lifecycle for reporting purposes, or modify the state of the runner (by perhaps changing options, adding tests, or disabling existing tests).

It is unlikely that cr_assert will ever work in those hooks because they are not designed to run in the runner, but that does not mean that there should not be a mechanism for aborting the runner in the future.

Right now however, the way report hooks are implemented makes this difficult to implement soundly, and as they are to be deprecated for a new hook API that matches the [protocol definition](https://github.com/Snaipe/Criterion/blob/bleeding/src/protocol/criterion.proto) (i.e. a hierarchical tree of tests and subtests described as phases), any real effort to implement this will be done after the 2.3.0 release.

In the meantime, the best thing to do would be to document that aborting the runner with any means from a report hook is unsupported, and the best course of action would be to explicitely disable all subsequent tests.

**Comment by Snaipe** [comment]
I don't think I'm going to implement this. Ultimately, report hooks are only for any kind of reporting work, in my opinion, as they cannot interfere with the tests workers.

If something needs to be asserted before everything, it makes more sense to have it execute in the test workers themselves.
