### ISSUE TITLE
On 32-bit Linux bxf_arena_init() can't mmap memory and dies with SIGSEGV

### ISSUE THREAD

**Issue by davemaleni** [Snaipe/Criterion#176]
I tried running code with 10 tests on 32-bit Linux (Ubuntu 16.04.1) and approximately 1 of 10 runs manages to finish without error message or a crash. Errors happen in approx. 20% cases when the first call to bxf_context_init() doesn't succeed. The rest are crashes when arena has value 0x666, so the check in arena_valid() generates SIGSEGV when it tries to dereference that address. I'm not quite sure why exactly this happens instead of exit withe the error message. Could be that the return value of bxf_arena_init() isn't checked somewhere.

Anyway, I've played with the code a bit and found values which work for me. I don't understand what's the purpose of randomizing memory segment address, so I don't know if those values are OK or not.

I've first added debug fprintf() statements and run the program in the loop to get successful memory allocations. Then I've changed mmap_base, mmap_max and r to force them into into the valid region. 
[boxfort_arena.c.txt](https://github.com/Snaipe/Criterion/files/564131/boxfort_arena.c.txt)

**Comment by Snaipe** [comment]
Interesting. I'll try to experiment a bit more with those values and perhaps try to get valid ranges from `/proc/self/maps` where applicable.

> Anyway, I've played with the code a bit and found values which work for me. I don't understand what's the purpose of randomizing memory segment address, so I don't know if those values are OK or not.

I've always disliked doing that manually when admitedly mmap randomizes the new mapping by itself, however on a lot of implementations (most notably Linux, OS X and FreeBSD) mmap stuffs the mapping with all other maps at the end of the address space, which prevents resizing without moving the map. So, yeah, unless there's a better alternative out there, I'm stuck with manually randomizing the mapping start address.

5 big pages worth of memory should be OK for the moment though, so I don't see why the range 0x40000000-0xa0000000 wouldn't be appropriate. This is a bit weird though since the calls to msync should have checked if the region was valid. Do you perhaps have a self-contained example that triggers the issue (even if once every 10 runs)?

**Comment by davemaleni** [comment]
This crashes once in about 5-10 runs. Even without the init function. Or says:

criterion: Could not initialize inheritable arena: Cannot allocate memory

```
#include <criterion/criterion.h>
#include <stdlib.h>

void
srv_init(void)
{   
    char *p = malloc(1000);
}   

TestSuite(SParser, .init=srv_init);

Test(one)
{
    cr_assert_eq(0, 1);
}

```
