### ISSUE TITLE
creating custom asserts

### ISSUE THREAD

**Issue by bazsi** [Snaipe/Criterion#177]
I might be missing something, but I'd like to create a custom assert function, one that reports its __FILE__ and __LINE__ locations for the actual caller.

e.g. something like this:

```
static void _assert_mystuff(const char *file, int lineno)
{
  cr_expect_false_with_file_and_line(TRUE, file, lineno);
}
```

Instead of reporting the missed assert within the assert_mystuff() function, it would be great to pass the actual locations, with something like:

```
#define assert_mystuff() \
    _assert_mystuff(__FILE__, __LINE__);

```

Is something like this doable?

**Comment by Snaipe** [comment]
This is actually a bit tricky because of how the assert API is made portable.

The "good" way of doing your assertion would be to make a predicate function to evaluation whether or not the conditions of your assertion should pass or not, and then wrap that in a macro, like so:

```
static bool is_mystuff_ok() {
    return true;
}

#define assert_mystuff(...) cr_assert(is_mystuff_ok(), __VA_ARGS__)
#define expect_mystuff(...) cr_expect(is_mystuff_ok(), __VA_ARGS__)
```

This has the advantage of letting you use the format string parameter, but you can't specify a default assert message.

If you *really* want to be able to specify a custom filename and line, the only way at the moment would be to call `criterion_send_assert`, which is part of the internal API. You can use it, of course, but don't expect it to always work across versions.

I think #165 is a good occasion for rethinking for a way to allow for custom assertions with default messages.

**Comment by Snaipe** [comment]
Just as a follow-up, I'm implementing this through a `cr_assert_user(File, Line, Condition, [Format, ...])` macro in #182.

I'm not sure I'm going to make this work with default messages though -- I expect that implementors will do that logic themselves, and the current format string w/ parameters can achieve that. For more general-purpose operations, this is going to be done through assert specifiers rather than individual macros.

**Comment by bazsi** [comment]
Thanks. I dont understand the default messages portion of your response,
but the prototype looks good at first sight.

**Comment by Snaipe** [comment]
This is now implemented.

**Comment by Snaipe** [comment]
I'm not quite satisfied with the stability of bleeding to call it a proper release for now. I don't want to release a half-baked product.

I'll consider making a release candidate after going through the existing issues in the following weeks, if my times allows so. :)

**Comment by bazsi** [comment]
Thanks. Criterion is great, so thank you for doing it :)

**Comment by bazsi** [comment]
@Snaipe any updates? our testsuite in syslog-ng really suffers without the assertion features. would be a great improvement over the ugly macro hell we have now.
