### ISSUE TITLE
--debug option is throwing error  criterion: Could not spawn test instance

### ISSUE THREAD

**Issue by soumyajuit** [Snaipe/Criterion#185]
I am trying to use --debug option to enable GDB debugging with my UT binary.
But when I run my UT binary with the following options I am getting this error.

bin/test_ss -j1 --filter rdr/* --debug
<snip/>
criterion: Could not spawn test instance: No such file or directory
Aborted

Hence I am not able to attach my UT with gdb [ using target remote ]. Help needed.

**Comment by soumyajuit** [comment]
Not sure, but as far as I seen the source code. It looks like following could be the problem.

core/runner_coroutine.c "run_test()" function is throwing the error. After it initialize the "sp" struct with debugger option when "bxf_spawn_struct()" is getting called the error is getting generated.

**Comment by Snaipe** [comment]
I thought I fixed the message to be clearer, but it turns out I didn't.

bxf_spawn_struct returns ENOMEM when the debugging server executable associated to your compiler is missing from your system. This means that if you compiled with gdb, --debug will try to execute gdbserver, and with clang, lldb-server.

You can force a particular debugging server to be used with `--debug=gdb` or `--debug=lldb` for instance, if you compiled with clang and use gdb otherwise, but first, make sure you have the relevant debugging server installed on your system and available in your PATH.

In the meantime, I'm going to add a more useful message to the whole situation.

**Comment by soumyajuit** [comment]
Hey,
It solved the issue 👍 .

I have installed the GDB-server and the mentioned steps in the gdb-readme worked exactly. 

One point though in the readme it reads following..
./simple.c.bin --debug <<< starting with debug enabled.
gdb -q ./test <<< attaching GDB with the correct binary in the other terminal.

It would be better to keep same binary name in the both places ( only to reduce some confusion).

One more question  I couldn't find the definition of "bxf_spawn_struct" in the Criterion source. Is it part of some standard library ?

**Comment by Snaipe** [comment]
Ah, right, this needs to be fixed, too.

`bxf_spawn_struct` comes from [BoxFort](https://github.com/diacritic/BoxFort), which is my attempt at portable process sandboxing.

**Comment by soumyajuit** [comment]
Thanks a lot for the help 👍.
I am closing this issue.
