### ISSUE TITLE
Add support for disabling of tests on the fly

### ISSUE THREAD

**Issue by jswaro** [Snaipe/Criterion#187]
It is not possible today to do the following:

```C

int use_model_x;

TestSuite(..., ..., .disabled = use_model_x);
```
It would be ideal if at run-time, I could determine if some tests should not be run because there is no support for them. Compile time detection is out because this a function of how the software being tested is run, not the actual compilation of the software. Compiling the test application for two different runs also feels to be unnecessary.

**Comment by Snaipe** [comment]
`.disabled` is a bit too wonky for my taste to be honest. Sure, it's convenient because of the syntax, but I feel that we're restricting a lot of things because of its design (namely, all runtime computations, because we're dealing with a static struct).

Right now, you want to call `cr_skip` in a setup fixture for your test suite. I don't think there is currently a better approach in 2.3.

I think that the best way to improve this would be to make `cr_assume` work in regular tests by reimplementing it as sugar for some kind of `if (!condition) { cr_skip(); }`. That way, you could simply put a bunch of `cr_assume(X, "disabled because of X");` in a setup fixture or directly in a test.

**Comment by jswaro** [comment]
How does cr_skip work if you have .init functions at the suite level for initializing test environment for a suite of tests?

**Comment by Snaipe** [comment]
> How does cr_skip work if you have .init functions at the suite level for initializing test environment for a suite of tests?

It marks every test in the suite as skipped with the optionally provided message.

**Comment by jswaro** [comment]
Right ... but at what time does this happen?

```C 
suite_init(....) {
     if (cond)  
         cr_skip("message");
}
```

Is this type of construct given above going to work?

**Comment by jswaro** [comment]
I'll look into seeing if we can update to 2.3 for our project then. Thanks.

**Comment by Snaipe** [comment]
(Actually, I made a typo: it's `cr_skip_test`, not `cr_skip`.)
