### ISSUE TITLE
Compile for static linking

### ISSUE THREAD

**Issue by kubiajir** [Snaipe/Criterion#225]
Hi,
I would like to know if is possible to compile the project for static linking?  I need to create standalone binaries for RPI and not to compile/install/or copy *.so Critetion to each device.

**Comment by Snaipe** [comment]
Static linking with criterion is somewhat in the territory of "It should work, but you're on your own" as it has a few gotchas that makes it hard to support on all platforms.

Since you're on rpi, you'll have to do a few things:

1. Compile & install a static build of [BoxFort](https://github.com/diacritic/BoxFort/tree/arch/arm), using the arch/arm branch. You'll probably have to patch the CMakeLists.txt to let it recognize the architecture. Criterion uses the following options to compile it:
```
-DBXF_TESTS=OFF
-DBXF_SAMPLES=OFF
-DBXF_STATIC_LIB=ON
-DBXF_FORK_RESILIENCE=OFF
-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
"-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} -fPIC -fvisibility=hidden"
```
2. Change SHARED on [this line](https://github.com/Snaipe/Criterion/blob/bleeding/CMakeLists.txt#L161) to STATIC.

You'll also have to link against all of the dependencies manually when compiling the tests.

It'd probably be interesting to have a proper process to compile a static lib version, but there's a few things that need to be done to ensure that everything works a-ok, starting with adding the correct flags to [the criterion pkg-config file](https://github.com/Snaipe/Criterion/blob/bleeding/src/criterion.pc.in), but I never got the time to do that.

**Comment by kubiajir** [comment]
Thanks, I will try it.
