### ISSUE TITLE
crash in teardown should be error instead of warning

### ISSUE THREAD

**Issue by furiel** [Snaipe/Criterion#242]
```
#include <criterion/criterion.h>
#include <stdlib.h>

TestSuite(teardowncrash, .fini = abort);

Test(teardowncrash, empty) {
}
```

```
$ ./main
[----] Warning! The test `teardowncrash::empty` crashed during its setup or teardown.
[====] Synthesis: Tested: 1 | Passing: 1 | Failing: 0 | Crashing: 0 
○ echo $?
0
```

If there is a crash in the teardown of a suite, criterion still reports the testcase as success. 

- This can hide potential init/deinit-related bugs.
- if core file generation is enabled, the generated core file will block `make distcheck`(, having an unknown file in the repository that is not cleaned up by `make clean`) for autools users. If a project has lots of criterion tests, it is hard to detect which one crashed do to wrong return value and reporting.

Is it possible to handle the .fini the same way as in .init? If there is a crash in .init, criterion reports the failure correctly. The same should happen with .fini.

For example: https://github.com/balabit/syslog-ng/pull/1872, when the crash went undetected for a long time.

**Comment by Snaipe** [comment]
This is somewhat delicate, because the reason why a teardown crash was considered a warning and not a test failure, is that on a technical standpoint a teardown isn't testing anything. This is mostly apparent when introducing a tree-like structure to tests (which is how the runner now works), and a teardown failing the group would be misleading.

99a2c7ec7261ea1c343f968dc9af657b48e90c2b fixes this issue by making warnings exit with a nonzero status, which should get most toolchains to react appropriately.

All things considered, it might be reasonable to mark the group as "crashed" (rather than pass/fail) when either init or fini crash.

**Comment by furiel** [comment]
Thanks for the explanation! https://github.com/Snaipe/Criterion/commit/99a2c7ec7261ea1c343f968dc9af657b48e90c2b indeed solves the problem. I built the bleeding version of criterion and tried out on syslog-ng.
The patch worked great together with ctest: I found another silently crashing unit test in syslog-ng. :)
Can't wait the to see the patch it in the next criterion release.
