### ISSUE TITLE
Core file still generated with expected crash

### ISSUE THREAD

**Issue by furiel** [Snaipe/Criterion#243]
```
#include <criterion/criterion.h>
#include <stdlib.h>
#include <signal.h>

Test(teardowncrash, empty, .signal=SIGABRT) {
    abort();
}
```

```
$ ./main
[====] Synthesis: Tested: 1 | Passing: 1 | Failing: 0 | Crashing: 0 

$ ls | grep core
core
```

Even though the testcase runs correctly, because the abort signal is expected in this case, a core file is still generated. This makes make distcheck to fail(, having an unknown file in the repository that is not cleaned up by make clean) for autools users. If a project has lots of criterion tests, it is hard to detect which one crashed do to wrong return value and reporting.

Is it possible that criterion ensure core file is generated only when it is necessary, core file for expected signal should not be generated or cleaned up properly?

**Comment by Snaipe** [comment]
This sounds reasonable, but the issue is that I don't think I can selectively disable core dumps from Criterion. If I expect a test to crash with SIGBUS, for instance, then call ulimit to disable core dumps, and the test crashes with SIGSEGV, then no core file will be produced.

You might consider having /proc/sys/kernel/core_pattern set, so that core files are put somewhere else that would make autotools happy.

**Comment by furiel** [comment]
Thanks for the explanation. I understand we still need the core if the test crashes with unexpected signal. I cannot come up with any reliable solution either. I checked what gtest does in this case, and gtest also generates core file even if the signal was expected. Probably it would be the task of a test driver to properly cleanup. I close this ticket, and go with the workaround.
