### ISSUE TITLE
2.3.3 release missing compiled binaries

### ISSUE THREAD

**Issue by Kokan** [Snaipe/Criterion#272]
The previous releases also had criterion compiled and not just the source uploaded.
Does you plan on continuing that practice ?
The syslog-ng project depends on those pre compiled files see: https://github.com/balabit/syslog-ng/blob/master/dbld/images/helpers/dependencies.sh#L17

**Comment by Snaipe** [comment]
It looks like the deploy shim on travis failed to upload the binary releases. I'll add them manually.

**Comment by Snaipe** [comment]
I have built the release manually on Ubuntu trusty and uploaded it. In hindsight, building these releases on travis is a bit of a bad idea, because libc ABI variations happen and can leave the library broken on some distributions. I'll see if I can figure something out for that, but I think the best solution would be to start pushing for packaging criterion in distributions directly.

I also don't have a Windows & OS X dev setup right now, so I can't upload binary releases for those right now, but I think I can retrieve the artifacts from Appveyor, so I'll probably be able to at least upload the windows release.

**Comment by MrAnno** [comment]
@Snaipe Perfect, thanks! :)

**Comment by Kokan** [comment]
Thanks, oh yeah official package would be the best.
