### ISSUE TITLE
Protocol error on arm64

### ISSUE THREAD

**Issue by jonathanturcotte** [Snaipe/Criterion#312]
I've compiled Criterion v2.3.3 from source on an ubuntu16 arm64 image without issue, but trying to run even the simplest test results in:

```
criterion: Re-entering criterion from a test worker. This is a catastrophic bug, please report it on the issue tracker.
Bailing out to avoid fork-bombing the system.
criterion: Could not spawn test instance: Protocol error
Aborted (core dumped)
```

Some version information:
```
ubuntu@ip-172-30-4-244:~/criterion$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23

ubuntu@ip-172-30-4-244:~/criterion$ gcc --version
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

ubuntu@ip-172-30-4-244:~/criterion$ cmake --version
cmake version 3.5.1

ubuntu@ip-172-30-4-244:~/criterion$ uname -a
Linux ip-172-30-4-244 4.15.0-1045-aws #47~16.04.1-Ubuntu SMP Fri Aug 2 16:23:47 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

Let me know if there's anything else I can do to help track down the issue!

**Comment by Snaipe** [comment]
Can you compile & install the latest [BoxFort](https://github.com/Snaipe/BoxFort) commit and use it to build Criterion (make sure to wipe the build dir)? Just to be sure this isn't something that got fixed somewhere there.

Are you able to reproduce this on qemu-user and/or qemu-system? This would help to know if this is something I can debug without buying some arm64 hardware.

**Comment by jonathanturcotte** [comment]
I can't seem to get the latest commit of BoxFort to compile on that box:

```
ubuntu@ip-172-30-4-164:~/BoxFort$ mkdir build && cd build
ubuntu@ip-172-30-4-164:~/BoxFort/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for _r_debug
-- Looking for _r_debug - found
-- Looking for _DYNAMIC
-- Looking for _DYNAMIC - found
-- Looking for PR_SET_PDEATHSIG
-- Looking for PR_SET_PDEATHSIG - found
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for CLOCK_MONOTONIC_RAW
-- Looking for CLOCK_MONOTONIC_RAW - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for environ
-- Looking for environ - found
-- Looking for mincore
-- Looking for mincore - found
-- Checking prototype mincore for HAVE_UNSIGNED_MINCORE_VEC - True
-- Looking for pthread_cond_timedwait_relative_np in pthread
-- Looking for pthread_cond_timedwait_relative_np in pthread - not found
-- Looking for trunc in m
-- Looking for trunc in m - found
-- Looking whether assembler supports `.hidden test`
-- Looking whether assembler supports `.hidden test` - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
CMake Error at CMakeLists.txt:187 (add_library):
  Cannot find source file:

    src/asm/trampoline-arm64.S

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: boxfort
CMake Error: Cannot determine link language for target "boxfort".
-- Generating done
-- Build files have been written to: /home/ubuntu/BoxFort/build
```

Looks like commit b926a6d broke cmake configuration for me, but even the commit before I can't actually compile:

```
ubuntu@ip-172-30-4-164:~/BoxFort/build$ cmake --build .
Scanning dependencies of target boxfort
[  5%] Building ASM object CMakeFiles/boxfort.dir/src/asm/trampoline-arm64.S.o
In file included from /home/ubuntu/BoxFort/src/asm/trampoline-arm64.S:25:0:
/home/ubuntu/BoxFort/src/asm/mangling.h:37:25: fatal error: mangling/BXF_MANGLING.h: No such file or directory
compilation terminated.
CMakeFiles/boxfort.dir/build.make:62: recipe for target 'CMakeFiles/boxfort.dir/src/asm/trampoline-arm64.S.o' failed
make[2]: *** [CMakeFiles/boxfort.dir/src/asm/trampoline-arm64.S.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/boxfort.dir/all' failed
make[1]: *** [CMakeFiles/boxfort.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

I do know that 926bd4c works though, because that's what Criterion builds as a dependency.

I'll give qemu a try following this guide : https://wiki.ubuntu.com/ARM64/QEMU

**Comment by Snaipe** [comment]
I'm in the process of phasing out cmake, but I'm not sure why it does not recognize your assembler program. Could you try giving `meson` a try at building?

```
$ pwd
/path/to/boxfort.git
$ meson ./build
$ ninja -C ./build
$ sudo ninja -C ./build install
```

**Comment by jonathanturcotte** [comment]
```
ubuntu@ip-172-30-4-234:~/BoxFort$ meson ./build
The Meson build system
Version: 0.29.0
Source dir: /home/ubuntu/BoxFort
Build dir: /home/ubuntu/BoxFort/build
Build type: native build

Meson encountered an error in file meson.build, line 121, column 0:
lexer
```
:(

I see that meson is on 0.52 now, so I'll see if I can get a newer version compiled on here. 0.29 is old.

**Comment by jonathanturcotte** [comment]
Installing the latest meson fixed that issue for me. Unfortunately even after compiling/installing the latest BoxFort, and then recompiling and reinstalling Criterion I still get the same error. I verified that cmake found the installed version of BoxFort and did not compile and use the old version.

I'll have a look at seeing if I can get qemu up and running with the ubuntu16 cloud image.

**Comment by jonathanturcotte** [comment]
Sorry for the delay, qemu/cloud-init weren't cooperating and I got pulled away on some other things. 

This morning I managed to get qemu up and running by (mostly) following [this guide](https://gist.github.com/george-hawkins/16ee37063213f348a17717a7007d2c79) on an ubuntu 19.04 host, using the ubuntu 16.04 cloud image found [here](https://cloud-images.ubuntu.com/releases/xenial/release/). 

Unfortunately I couldn't reproduce the issue in this qemu instance, even though it should be the same ubuntu16 cloud image that I was using in AWS. This leads me to believe that it's an issue specific to AWS' A1 cloud instances, which run [some custom AWS Graviton arm processor](https://aws.amazon.com/blogs/compute/getting-started-with-the-a1-instance/).

Let me know if there's anything else I can do!

**Comment by Snaipe** [comment]
Well that's a shame. I'll have a look at spinning up the same environment and debugging this, though I have no idea how much time this is going to take me.

Before I do though, I think I need to clear up how this can happen on real hardware vs qemu. Something is really strange here.

The reason you're seeing `criterion: Re-entering criterion from a test worker. This is a catastrophic bug, please report it on the issue tracker` means that criterion was able to find a `main` symbol *but* that in reality it wasn't the address of the function. This means that criterion patched some random memory with the test worker trampoline instead of the start of the main function, which in turn makes worker initialization fail.

This is typically not a hardware vs emulator problem, which is why I find the fact that it's passing on qemu troubling.

However, `main` is a dynamic symbol in libcriterion.so, which means that any pointer to it gets patched by the dynamic linker during program initialization. This is usually how we end up sure that we have the right address to patch: ld.so does that for us.

That would mean that there is a difference between the cloud image you used and the image AWS claims to be running. It wouldn't be the first time I see a cloud provider using a patched kernel or dynamic linker, so I don't think it's too far fetched.

One of the things I need to see is if there is any discrepancy between the address of main that criterion (or rather, boxfort) gets and where that function is in reality. In that aspect, running a gdb script that 1) adds a breakpoint on main, then runs the program and prints the address it stops at and 2) adds a breakpoint in boxfort to print the value of [addr](https://github.com/Snaipe/BoxFort/blob/master/src/exe-elf.c#L206) would help me get an idea if the above hypothesis is remotely true.

**Comment by MrAnno** [comment]
It almost drove me crazy, but I've finally found the issue here (it seems my Christmas present was an ARM Cortex-A72 and a few hours with an Apple M1 machine 😄).

The trampoline injection code is perfect, but the trampoline instructions were extremely fragile and unpredictable. This could not be reproduced on an emulator.

It turned out that the injected payload was sometimes "skipped", and the CPU started to execute instructions after the unconditional jump, which is impossible. The issue was with CPU cache lines, a `__builtin___clear_cache()` call fixed all the weird behavior.

I'm opening a PR soon.
