### ISSUE TITLE
Repository file does not have a Realease file

### ISSUE THREAD

**Issue by 1t3x** [Snaipe/Criterion#317]
Hello,
When adding the PPA repo I am given this error
`E: The repository 'http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu eoan Release' does not have a Release file.`

**Comment by Snaipe** [comment]
That's because launchpad does not rebuild Criterion for new debian/ubuntu releases. I haven't figured out yet how to best tackle that, and maintaining the PPA is somewhat low-priority with my limited time at the moment.

If Criterion is something you'd like to see in your distribution, please reach out their package maintainers, I can work with them to figure out what needs to be done to build a package for it. On Debian, you can make a Request For Package (RFP): https://www.debian.org/devel/wnpp/

**Comment by Snaipe** [comment]
Criterion is now packaged in Debian.
