### ISSUE TITLE
Implement an extended globbing parser

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#42]
Currently, the extended globbing is transformed by the algorithm in `extmatch.c` to a perl regexp, which is then passed to PCRE.

It would probably be better to cut the middle ground and do the parsing ourselves -- this would remove PCRE as a dependency and provide `--pattern` on all platforms.

**Comment by am11** [comment]
One less dependency would definitely be a nice improvement.

/opinion-time :)
Here are some thoughts:

* For Unix, `<glob.h>` can be used, while on Windows there is [this API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418.aspx) and its extended [version](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364419.aspx).
  For Windows, it would probably require to link `[w]setargv.obj` in order to pass glob pattern charachters via `argv[]`: http://stackoverflow.com/a/1269533/863980. 

* Down the road, (in addition to CLI arg `--pattern`) would be nice to incorporate `.criterionignore` -- `.*ignore` files are usually flat files with `[CR]LF`-separated pattern list, such as; `.gitignore`. 

  ```
  **/*.ignore.*
  **/*todo/**
  !**/active-todo/**
  ```

* Similarly `.criterionrc` -- `.*rc` files are usually JSON-based settings file with exception to support inline comments (which std JSON disallows), e.g. [.jshintrc](https://github.com/jshint/jshint/blob/92e1a60/examples/.jshintrc). JSON may sound like a beg for another dependency, but a simple custom tokenizer would do a job to extract keys & values of supported options separated by `:` & escaped by `"` at a single hierarchy (no nesting). Some linters also support nesting ignore files within settings.

  Random example:
  ```json
  // Criterion settings file: .criterionrc

  {
    "max-timeout": 200,
    "coverage": true,
    "coverage-template": "/path/to/template",
    "ignore-files" :
    [
      "**/*.ignore.*",
      "**/*todo/**",
      "!**/active-todo/**"
    ]
  }
  ```

**Comment by Snaipe** [comment]
> For Unix, <glob.h> can be used, while on Windows there is this API and its extended version.
For Windows, it would probably require to link [w]setargv.obj in order to pass glob pattern charachters via argv[]: http://stackoverflow.com/a/1269533/863980. 

`glob.h` can't be used as it does not support extended globbing (we used `fnmatch.h` in older versions).
The windows API version works on files rather than strings, so it wouldn't really fit the task.

Configuration files could definitely be possible.

I'm all for writing my lexers and parsers, but I'd like to reduce the possible amount of bugs and maintainance on those parts, so I'm wondering if I should use bison and flex to generate parsers/lexers for both extglob and json. This wouldn't really add another hard dependency, as I can commit the generated file along with the definition files, commiting both kinds when changing something.

**Comment by a1lu** [comment]
Regarding the config file:
https://gist.github.com/justjkk/436828
This is a MIT licensed JSON parser.
