### ISSUE TITLE
Theories not working

### ISSUE THREAD

**Issue by MartinBourbier** [Snaipe/Criterion#437]
Hey!

I tried to add theories in a project of mine but the permutations don't seem to work.

As you can see on the screenshot below, the values are always the same (the first two, both 0s).

![in](https://user-images.githubusercontent.com/89635684/161461560-7dde7668-8a73-4a62-9c04-a262f839e871.png)
![out](https://user-images.githubusercontent.com/89635684/161461564-89633af7-a0ca-452c-ae43-20abef19dacf.png)

And I am following the doc.

Am I missing something?

**Comment by Snaipe** [comment]
Could you tell me which version of Criterion you are using? Did it come from some upstream repository or did you build it from source?

**Comment by Snaipe** [comment]
I can reproduce this, it must have regressed during the libffi transition. Looking.

**Comment by Snaipe** [comment]
It looks like during the move to libffi, I forgot to reset the argument vector. I think this got missed because the new assert API changed the output format, and the new tests were taking the new incorrect behavior as the new ground truth.

Can you try out the linked pull request (#440) to see if this fixes it for you too?

**Comment by MrAnno** [comment]
@MartinBourbier You can recompile Criterion by following the same steps in the documentation, but using the following command to clone the repository:

```
$ git clone --recursive https://github.com/Snaipe/Criterion --branch fix/theory-ffi-argv
```

**Comment by MartinBourbier** [comment]
Just tested, works fine on my end!

Thanks!
