### ISSUE TITLE
Monterey logs warnings for every test run

### ISSUE THREAD

**Issue by CamJN** [Snaipe/Criterion#438]
When I run my test suite on macOS 12, I get the following message for every test I run (with different values in the brackets):

`tests(21765,0x10d9ca600) malloc: nano zone abandoned due to inability to preallocate reserved vm space.`

**Comment by Snaipe** [comment]
Do you have address or thread sanitizer enabled with the test by any chance?

If not that, then the arena code seem to be a likely contender for any conflicts with nano_malloc. If it's this, then I'm not sure how we can really fix it, or whether we should. I guess we could try to either not impede with the start of `NANOZONE_SIGNATURE` at the risk of tiptoeing into the thread/address sanitizer address space, but I'm almost tempted to just export `MallocNanoZone=0` as an environment variable when starting test processes with BoxFort.

**Comment by CamJN** [comment]
Ah yes, I do use Asan and UBsan (not thread sanitizer as my program is single threaded). Is that simply incompatible or is there something I can do to make it get along?

Interestingly this didn't occur when I was on Big Sur. The upgrade to monterey did come with a clang upgrade:

Big Sur / Clang 12 - no warning
Monterey / Clang 13 - warning

**Comment by Snaipe** [comment]
I've seen quite a few reports about nano_malloc printing this warning when `-fsanitize=address` is in use, and I think this likely happened because libmalloc.so got this new preallocation behavior in Montery. Can you double-check that the warning prints with this simple program, compiled with `-fsanitize=address`?

```c
#include <stdlib.h>

int main(void) {
   volatile int *ptr = malloc(sizeof (*ptr));
   *ptr = 42;
   return 0;
}
```

If so, then I think the best solution is to export `MallocNanoZone=0` prior to running the test program. BoxFort doing that automatically seem like an overreach, since it'd be disabling the preallocation for programs not compiled with the address sanitizer, and changing behavior between real execution and test execution is usually not a good idea for consistency.

**Comment by CamJN** [comment]
Yup, can confirm that program prints the warning when compiled with `-fsanitize=address`, doesn't when `MallocNanoZone=0` is set in the env, and also doesn't when compiled without `-fsanitize=address`.

**Comment by CamJN** [comment]
Anyway looks like this isn't a _criterion_ issue at all, so I'll close.
