### ISSUE TITLE
Feature request:  cr_assert_crash( a function that we expect to crash )

### ISSUE THREAD

**Issue by marknelsonengineer-student** [Snaipe/Criterion#541]
Criterion is great for most unit test scenarios, but it doesn't seem to have the ability to assert that a crash is an expected behavior.

I like to write code with a lot of `assert()` code from `<assert.h>`.  I'd like to write tests to ensure that my `assert()` code works.  Criterion tells me that the code crashed... which is great, but now I'd like a `cr_assert` function that makes that expected behavior... and dings me if the program **does not** crash.

Thank you for considering this change request.

**Comment by rgomes1** [comment]
Hi,

There is a directive you can specify for this, such as:
.signal = SIGSEGV
as an option in the Test macro interface. With this declared, when the code being unit tested issues a SIGSEGV, because you declared this was the expected result, the test passes.

This is also described in the Criterion documentation:
https://readthedocs.org/projects/criterion/downloads/pdf/latest/
(see page 9)

**Comment by marknelsonengineer-student** [comment]
Thank you.  I got this working.  I'll close this ticket.
