### ISSUE TITLE
Feature request: Set output format with an environment variable

### ISSUE THREAD

**Issue by porglezomp** [Snaipe/Criterion#79]
I'm using Criterion with an Autotools based project and I want to aggregate the results of multiple test programs. Running the tests with TAP under the `tap-driver.sh` seems to be the recommended method, but Automake doesn't allow you to pass any arguments to your tests.

It'd be great if I could just set `CRITERION_OUTPUT_FORMAT=TAP` or something similar before the tests run in order to get TAP output.

**Comment by Snaipe** [comment]
For 2.1.1 and prior, you can use `CRITERION_ENABLE_TAP=1` to do so -- however the environment variable has been temporarily removed on bleeding because of some fundamental changes on how the reporters are implemented.

I'll bring this back for compatibility purposes, so you should be able to use this environment variable.

(keeping this issue open as a reminder)

**Comment by Snaipe** [comment]
Implemented. ``CRITERION_ENABLE_TAP`` is back (although deprecated), and I added ``CRITERION_OUTPUTS`` for more extensive purposes.
