### ISSUE TITLE
Add -j0 option to disable fork()

### ISSUE THREAD

**Issue by ckaran** [Snaipe/Criterion#83]
Can you please add a `-j0` option to fully disable `fork()`?  My problem is that [LLDB](http://lldb.llvm.org/) doesn't play well with child processes (possibly other debuggers as well).  This means that sometimes my only option for figuring out **WHY** something is failing is lots of `printf()` statements.  By adding the ability to run everything in the main process, debuggers will be a real option.

**Comment by Snaipe** [comment]
This has a bit in common with issue #69, namely the ability to run a single test in client mode (here for debugging purposes).

In this case, one would simply add ``--client=suite::test``to run this specific test without forking.

Allowing fork to be globally disabled would be a huge deal breaker, as a lot of the current functionality of criterion relies on the complete isolation of a test in its own address space, so I doubt such a feature will ever be available.

It's a shame that LLDB doesn't really have an equivalent of GDB's follow-fork-mode, but you have a point. Tests are also a bit tricky to debug on Windows.

**Comment by ckaran** [comment]
If there was a way to run one particular test without forking, that would be good enough; would it be possible to do that relatively easily?

**Comment by Snaipe** [comment]
It should be easy to do. The hardest thing here would be to properly handle parameterized tests by extending the syntax of ``--client`` in order to specify what parameter should be used.

**Comment by ckaran** [comment]
Is --client a current option of Criterion-based tests?  I just pulled and installed the latest `bleeding`-branch, and my compiled test doesn't have a --client option.

**Comment by Snaipe** [comment]
Not yet, when talking about extending the syntax, I was refering to the ``--client=suite::test`` syntax I mentioned above.

**Comment by ckaran** [comment]
Got it; I got hopeful! :)

**Comment by Snaipe** [comment]
If you need an ETA on when this should hit bleeding, I'd say this friday. Hope this doesn't really slow you down.

**Comment by D3Hunter** [comment]
`set follow-fork-mode child` is not working, it just run the test and did't break at breakpoint. I have tried 
`set detach-on-fork off`, still not working, Right now i have to add `kill(getpid(),SIGSTOP)` into the the unit-test that was failing, in order to debug it, really need a convenient way to do this,  any suggestions?

Below is the output:

Note: `ini_getstr` is the function i'm testing

    (gdb) b ini_getstr 
    Breakpoint 2 at 0x40be3d
    (gdb) set follow-fork-mode child
    (gdb) r
    Starting program: /root/work/php-agent/tests/unit_test 
    [Thread debugging using libthread_db enabled]
    [New process 18598]
    [Thread debugging using libthread_db enabled]

    Program exited normally.
    (gdb) [====] Synthesis: Tested: 3 | Passing: 3 | Failing: 0 | Crashing: 0 

    (gdb) set detach-on-fork off
    (gdb) r
    Starting program: /root/work/php-agent/tests/unit_test 
    [Thread debugging using libthread_db enabled]
    [New process 18610]
    [Thread debugging using libthread_db enabled]

    Program exited normally.
    (gdb)

**Comment by Snaipe** [comment]
@D3Hunter Hm, this is weird, I can break inside the test on my end.

For the record, if you try to compile ``samples/simple.c``, open it in gdb, set ``follow-fork-mode`` to ``child`` and put a breakpoint on ``misc_failing_impl``, does it work?

Also, what OS are you on / what compiler & version are you using / what gdb version are you using?

**Comment by D3Hunter** [comment]
Run with shared build, it's working and stopped at the breakpoint.

    (gdb) set follow-fork-mode child
    (gdb) b misc_failing_impl
    Breakpoint 1 at 0x40080c
    (gdb) r
    Starting program: /root/code/Criterion/samples/a.out
    [Thread debugging using libthread_db enabled]
    [New process 20449]
    [Thread debugging using libthread_db enabled]
    [Switching to Thread 0x2aaaaaccf5a0 (LWP 20449)]

    Breakpoint 1, 0x000000000040080c in misc_failing_impl ()
    (gdb) q

Run with static build, don't break. (I build a static library myself)

    (gdb) set follow-fork-mode child
    (gdb) b misc_failing_impl
    Breakpoint 1 at 0x4084fc
    (gdb) r
    Starting program: /root/code/Criterion/samples/a.out 
    [Thread debugging using libthread_db enabled]
    [New process 20495]
    [Thread debugging using libthread_db enabled]

    Program exited normally.
    (gdb) [----] simple.c:4: Assertion failed: The expression 0 is false.
    [FAIL] misc::failing: (0.00s)
    [====] Synthesis: Tested: 3 | Passing: 2 | Failing: 1 | Crashing: 0 

    (gdb) 
    (gdb) q

**Comment by Snaipe** [comment]
@D3Hunter This is indeed weird, although officially statics builds are not supported (for various reasons, the first one being dependencies not included)

**Comment by Snaipe** [comment]
@ckaran I implemented it as ``--single`` (because ``--client`` in a client/server context will probably do more and I don't want to break compatibility).

An other idea I'm thinking of would be to maybe implement an interactive mode, where one would be able to run a test in debug mode, and criterion stops the worker + give its pid for remote debugging.

**Comment by D3Hunter** [comment]
@Snaipe In `runner.c`, there is a test-case `Test(,) {};` to prevent `cr_tst` section empty(also an empty `TestSuite();`). With shared build, this is fine for the executable'll have a different `cr_tst` section with `libcriterion.so`. But with static build, this  will add a empty test to the test-case list, that's why there 2 cases while only one case has been written as shown below:

    [====] Synthesis: Tested: 2 | Passing: 1 | Failing: 1 | Crashing: 0 

Because of this, with `set follow-fork-mode child` set, the first child run will be this empty test-case, so the breakpoint will never stopped as `gdb` only catches the first child.

So why have to keep section `cr_tst` non-empty?
Also, is there any plans to support `static-build` in the future release?

**Comment by Snaipe** [comment]
@D3Hunter this is indeed a problem since this empty placeholder test should have been ignored. I'm going to try another fix.

On your question about static builds, generally there won't be any support towards supporting them, as the static vs shared build only makes sense when distributing binaries (so as to include your dependencies in the final binary or not), and unit testing is not one of those cases.

**Comment by Snaipe** [comment]
The above information also helped me realize that gdb will always follow the first child in a ``follow-fork-mode child`` context, so debugging with gdb is virtually not possible unless you break in the parent before running the desired child, then set ``follow-fork-mode child``.

Hopefully the addition of ``--single`` and (maybe) later an interactive debugging mode should make debugging less painful.

**Comment by ckaran** [comment]
@Snaipe Is `--single` in the bleeding branch?  I just pulled and didn't see it.

Also, I just started #85 to hold any ideas for interactive debugging.

**Comment by Snaipe** [comment]
Yes, it is, although not (yet) documented.
